version: '3.8'

services:
  food-order-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional: Add a database service if you want to use external DB
  # h2-db:
  #   image: oscarfonts/h2
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     - H2_OPTIONS=-web -webAllowOthers -tcp -tcpAllowOthers -browser
  #   restart: unless-stopped
